### ISSUE TITLE
While following the tutorial, floodlight give me an exception

### ISSUE THREAD

**Issue by aanm** [floodlight/floodlight#438]
Hello, I was following the following tutorial http://docs.projectfloodlight.org/display/floodlightcontroller/How+to+Write+a+Module
And on the Register The Module part the floodlight give me the following exception:
<==============================================>
mininet@mininet-vm:~/floodlight$ java -jar target/floodlight.jar 
13:24:43.898 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading default modules                                                                                                                                                              
Exception in thread "main" net.floodlightcontroller.core.module.FloodlightModuleException: ERROR! The configuraiton file specifies more than one module that provides the service net.floodlightcontroller.core.IFloodlightProviderService. Please specify only ONE of the following modules in the config file: net.floodlightcontroller.core.internal.FloodlightProvider, net.floodlightcontroller.mactracker.MACTracker,                                                               
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.findAllModules(FloodlightModuleLoader.java:146)                                                                                                                       
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:259)                                                                                                                  
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:362)                                                                                                                  
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:200)
        at net.floodlightcontroller.core.Main.main(Main.java:55)
<==============================================>

I tried to comment the "net.floodlightcontroller.core.internal.FloodlightProvider" and didn't work, another exception is thrown:
<==============================================>
mininet@mininet-vm:~/floodlight$ java -jar target/floodlight.jar 
13:34:09.626 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading default modules
Exception in thread "main" net.floodlightcontroller.core.module.FloodlightModuleException: Module net.floodlightcontroller.core.internal.FloodlightProvider not found
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:278)
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:362)
        at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:200)
        at net.floodlightcontroller.core.Main.main(Main.java:55)
<==============================================>

**Comment by rizard** [comment]
@aanm @coolws FWIW, Floodlight v1.0 now supports OpenFlow 1.3.

**Comment by hengmuling** [comment]
so,where is the solution?

**Comment by FP-Guitar** [comment]
> so,where is the solution?

Actually, i suspect that you accidentally implemented getModuleServices() instead of getModuleDependencies(). I made this mistake, resulting in exactly the same error message.
