### ISSUE TITLE
change master to slave 

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#513]
GET http://localhost:8080/wm/core/role/json

    {"role":"ACTIVE","change-description":"Controller startup.","change-date-time":1427880917184}

POST http://localhost:8080/wm/core/role/json  Header content-type: application/json

    {"role":"ACTIVE","change-description":"Controller startup.","change-date-time":1427880917184}

Error message: 

An exception occured writing the response entity
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationConfig.SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: org.restlet.data.Status["throwable"]->com.fasterxml.jackson.databind.JsonMappingException["location"]->com.fasterxml.jackson.core.JsonLocation["sourceRef"])
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:57) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:544) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:551) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:143) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:544) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:551) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:143) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:544) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:551) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:143) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:224) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:612) ~[floodlight.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:497) ~[floodlight.jar:na]
	at org.restlet.ext.jackson.JacksonRepresentation.write(JacksonRepresentation.java:464) ~[floodlight.jar:na]
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:510) ~[floodlight.jar:na]
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454) ~[floodlight.jar:na]
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187) ~[floodlight.jar:na]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144) [floodlight.jar:na]
	at org.restlet.ext.simple.internal.SimpleContainer.handle(SimpleContainer.java:74) [floodlight.jar:na]
	at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121) [floodlight.jar:na]
	at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103) [floodlight.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]

**Comment by wenxueliu** [comment]
at  the commit point of  a2ac42e923b8f4beae965acffd6b4dd1ca28d419

    [n.f.c.i.Controller:Dispatcher: Thread-15] Received role request to transition from MASTER to  SLAVE (reason: <none>). Terminating floodlight.

**Comment by wenxueliu** [comment]
I have make it work at the commit point of a2ac42e. but I wonder why it protected floodlight role from mast to slave.  the code location the  856  of Controller.java 

            if (this.role == Role.MASTER && role == Role.SLAVE) {
                log.info("Received role request to transition from MASTER to "
                          + " SLAVE (reason: {}). Terminating floodlight.",
                          roleChangeDescription);
                System.exit(0);
            }

**Comment by wenxueliu** [comment]
In the IHAListener.java I find fllow information :

      "<strong>NOTE:</strong> The floodlight platform currently does not support  a transition to the STANDBY role. " 

is it true ?

**Comment by rizard** [comment]
That's correct. Please post questions to the mailing list rather than opening an issue.

Standby mode effectively only lets the controller listen and not act on any events. So, the default behavior of starting Floodlight in standby/slave mode is to shut down. This behavior can be easily modified though. Send a note to floodlight-dev@openflowhub.org and we can help you out.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
@wenxueliu If you want to set a switch role as master/slave/equal, then use GET/POST to the REST API /wm/core/switch/<dpid-or-"all"/role/json. I'm working on support for HA role as standby/slave, but it's more difficult than switch roles. If you'd like to make suggestions or help out, it would be much appreciated!
