### ISSUE TITLE
Floodlight start error

### ISSUE THREAD

**Issue by Catalin92** [floodlight/floodlight#545]
Hi all,
I am new in using floodlight and i can not find what is wrong .
I installed floodlight and when i try start i get this:

floodlight# java -jar target/floodlight.jar
20:00:47.715 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading modules from src/main/resources/floodlightdefault.properties
20:00:48.177 WARN [n.f.r.RestApiServer:main] HTTPS disabled; HTTPS will not be used to connect to the REST API.
20:00:48.179 WARN [n.f.r.RestApiServer:main] HTTP enabled; Allowing unsecure access to REST API on port 8080.
20:00:51.881 WARN [n.f.c.i.OFSwitchManager:main] SSL disabled. Using unsecure connections between Floodlight and switches.
20:00:51.882 INFO [n.f.c.i.OFSwitchManager:main] Clear switch flow tables on initial handshake as master: TRUE
20:00:51.882 INFO [n.f.c.i.OFSwitchManager:main] Clear switch flow tables on each transition to master: TRUE
20:00:51.883 INFO [n.f.c.i.OFSwitchManager:main] Setting 0x4 as the default max table to receive table-miss flow
20:00:51.915 INFO [n.f.c.i.OFSwitchManager:main] Setting max table to receive table-miss flow to 0x4 for DPID 00:00:00:00:00:00:00:01
20:00:51.916 INFO [n.f.c.i.OFSwitchManager:main] Setting max table to receive table-miss flow to 0x4 for DPID 00:00:00:00:00:00:00:02
20:00:51.924 INFO [n.f.c.i.Controller:main] Controller role set to ACTIVE
20:00:51.988 INFO [n.f.f.Forwarding:main] Default hard timeout not configured. Using 0.
20:00:51.988 INFO [n.f.f.Forwarding:main] Default idle timeout not configured. Using 5.
20:00:51.988 INFO [n.f.f.Forwarding:main] Default priority not configured. Using 1.
20:00:51.989 INFO [n.f.f.Forwarding:main] Default flow matches set to: VLAN=true, MAC=true, IP=true, TPPT=true
20:00:52.722 INFO [o.s.s.i.c.FallbackCCProvider:main] Cluster not yet configured; using fallback local configuration
20:00:52.723 INFO [o.s.s.i.SyncManager:main] [32767] Updating sync configuration ClusterConfig [allNodes={32767=Node [hostname=localhost, port=6642, nodeId=32767, domainId=32767]}, authScheme=CHALLENGE_RESPONSE, keyStorePath=/etc/floodlight/auth_credentials.jceks, keyStorePassword is unset]
20:00:52.984 INFO [o.s.s.i.r.RPCService:main] Listening for internal floodlight RPC on localhost/127.0.0.1:6642
20:00:53.071 INFO [n.f.c.i.OFSwitchManager:main] Listening for switch connections on 0.0.0.0/0.0.0.0:6653
20:00:53.093 INFO [n.f.l.i.LinkDiscoveryManager:main] Setting autoportfast feature to OFF
20:00:53.691 ERROR [n.f.core.Main:main] Exception in main
java.lang.RuntimeException: java.net.BindException: Address already in use
	at net.floodlightcontroller.restserver.RestApiServer$RestApplication.run(RestApiServer.java:176) ~[floodlight.jar:na]
	at net.floodlightcontroller.restserver.RestApiServer.run(RestApiServer.java:205) ~[floodlight.jar:na]
	at net.floodlightcontroller.core.Main.main(Main.java:63) ~[floodlight.jar:na]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_75]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_75]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_75]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_75]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.7.0_75]
	at org.simpleframework.transport.connect.SocketAcceptor.bind(SocketAcceptor.java:183) ~[floodlight.jar:na]
	at org.simpleframework.transport.connect.SocketAcceptor.<init>(SocketAcceptor.java:100) ~[floodlight.jar:na]
	at org.simpleframework.transport.connect.SocketListener.<init>(SocketListener.java:81) ~[floodlight.jar:na]
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:98) ~[floodlight.jar:na]
	at org.simpleframework.transport.connect.SocketListenerManager.listen(SocketListenerManager.java:81) ~[floodlight.jar:na]
	at org.simpleframework.transport.connect.SocketConnection.connect(SocketConnection.java:106) ~[floodlight.jar:na]
	at org.restlet.ext.simple.HttpServerHelper.start(HttpServerHelper.java:92) ~[floodlight.jar:na]
	at org.restlet.Server.start(Server.java:579) ~[floodlight.jar:na]
	at org.restlet.Component.startServers(Component.java:642) ~[floodlight.jar:na]
	at org.restlet.Component.start(Component.java:567) ~[floodlight.jar:na]
	at net.floodlightcontroller.restserver.RestApiServer$RestApplication.run(RestApiServer.java:174) ~[floodlight.jar:na]
	... 2 common frames omitted

Thx

**Comment by Sovietaced** [comment]
```
20:00:53.691 ERROR [n.f.core.Main:main] Exception in main
java.lang.RuntimeException: java.net.BindException: Address already in use
at net.floodlightcontroller.restserver.RestApiServer$RestApplication.run(RestApiServer.java:176) ~
```

You probably already have another instance of Floodlight running. Kill any processes using port 8080

**Comment by rizard** [comment]
@Catalin92 If you still have problems, try posting to the mailing list at floodlight-dev@openflowhub.org. @Sovietaced was pretty quick to respond here, but the list will typically get you help faster, since more people check that. Let us know if you have any further issues or when you resolve yours.

**Comment by Catalin92** [comment]
Thanks for answers.
I reinstalled all my programs(mininet , OVS, floodlight) and now it works . I am not sure what was wrong then but i don't think was a  problem with ports because i had same problem even after a restart(or kill -9 -1).

**Comment by rizard** [comment]
@Catalin92 Great to hear! I'll close this issue then. Feel free to reach out on the mailing list in the future if you have any problems getting up and running.

**Comment by shenaishiren** [comment]
I have already solved the problem, floodlight's config file is floodlight/src/main/resources/floodlightdefault.properties, when I open the config file,I find the port 8080,so I check the port I have used,as a result,I find I have use the port 8080 for nginx,so I kill the nginx process,then everything is ok.

**Comment by soniekta** [comment]
20:00:53.691 ERROR [n.f.core.Main:main] Exception in main
java.lang.RuntimeException: java.net.BindException: Address already in use
at net.floodlightcontroller.restserver.RestApiServer$RestApplication.run(RestApiServer.java:176) ~
what to do?

**Comment by Sovietaced** [comment]
> what to do?

Find out what is running on port 8080 and see if it can be killed. If it cannot be killed, adjust the property files to change the port that floodlight runs on.
