### ISSUE TITLE
Problem with importing project to InteliJIdea

### ISSUE THREAD

**Issue by phenomx64** [floodlight/floodlight#550]
I had made .project files for eclipse with "ant eclipse". My favorite IDE is InteliJIdea. I had imported it to InteliJ, but when i tried to run I get the following error :
"20:42:46.266 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading modules from src/main/resources/floodlightdefault.properties
20:42:46.303 ERROR [n.f.core.Main:main] Exception in main
net.floodlightcontroller.core.module.FloodlightModuleException: Module net.floodlightcontroller.jython.JythonDebugInterface not found
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.traverseDeps(FloodlightModuleLoader.java:337) ~[bin/:na]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:311) ~[bin/:na]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:259) ~[bin/:na]
	at net.floodlightcontroller.core.Main.main(Main.java:61) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
"

I removed the first line ["net.floodlightcontroller.jython.JythonDebugInterface,\"] and then it get stuck with the second ["net.floodlightcontroller.storage.memory.MemoryStorageSource,\"].
It could not found any floodlight modules and get stops.

Can anybody help me to fix this?

**Comment by phenomx64** [comment]
Exctracted the project zip file again. open the project file directly.
Errors are gone. Sorry everybody

**Comment by anandsingha** [comment]
root@keisamanand:/home/anand/floodlight-master# java -jar target/floodlight.jar 2019-08-29 18:45:20.843 INFO  [n.f.c.m.FloodlightModuleLoader] Loading modules from src/main/resources/floodlightdefault.properties
2019-08-29 18:45:20.987 ERROR [n.f.c.m.FloodlightModuleLoader] Could not find module: net.floodlightcontroller.core.module.IFloodlightModule: Provider net.floodlightcontroller.headerextract.HeaderExtract could not be instantiated
2019-08-29 18:45:20.989 ERROR [n.f.core.Main] Exception in main
net.floodlightcontroller.core.module.FloodlightModuleException: Module  not found
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.traverseDeps(FloodlightModuleLoader.java:313) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:287) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:235) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.Main.main(Main.java:61) ~[floodlight.jar:1.2-SNAPSHOT]

Kindly anyone help me to provide the solution. I shall be thankful.
