### ISSUE TITLE
Exceptions running mininet/examples/treeping64.py

### ISSUE THREAD

**Issue by mvanotti** [floodlight/floodlight#713]
Hi!
I'm trying to get floodlight running with mininet, in particular, I need to run > 100 nodes in my computer. There's an example of an all-pairs ping that I tried to run with floodlight as the controller, and I got some exceptions, the full log is > 20 MB, so I am just pasting the exception here.

[This is the test that I wanted to run](https://github.com/mininet/mininet/blob/master/examples/treeping64.py). [This is the actual script that I ran](http://pastebin.com/gCwZPr6U) (using floodlight as the remote controller).

This is my floodlight config:

```
floodlight.modules=\
net.floodlightcontroller.storage.memory.MemoryStorageSource,\
net.floodlightcontroller.core.internal.FloodlightProvider,\
net.floodlightcontroller.threadpool.ThreadPool,\
net.floodlightcontroller.staticflowentry.StaticFlowEntryPusher,\
net.floodlightcontroller.topology.TopologyManager,\
net.floodlightcontroller.forwarding.Forwarding,\
net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager,\
net.floodlightcontroller.devicemanager.internal.DeviceManagerImpl
net.floodlightcontroller.forwarding.Forwarding.match=vlan, mac, ip, transport
net.floodlightcontroller.forwarding.Forwarding.flood-arp=NO
net.floodlightcontroller.core.internal.FloodlightProvider.openFlowPort=6633
net.floodlightcontroller.core.internal.FloodlightProvider.role=ACTIVE
net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.latency-history-size=10
net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.latency-update-threshold=0.5
net.floodlightcontroller.core.internal.OFSwitchManager.defaultMaxTablesToReceiveTableMissFlow=1
net.floodlightcontroller.core.internal.OFSwitchManager.maxTablesToReceiveTableMissFlowPerDpid={"00:00:00:00:00:00:00:01":"1","2":"1"}
net.floodlightcontroller.core.internal.OFSwitchManager.clearTablesOnInitialHandshakeAsMaster=YES
net.floodlightcontroller.core.internal.OFSwitchManager.clearTablesOnEachTransitionToMaster=YES
net.floodlightcontroller.core.internal.OFSwitchManager.supportedOpenFlowVersions=1.0, 1.1, 1.2, 1.3, 1.4
```

And this is the log:

```
00:57:56.214 WARN [n.f.c.i.Controller:nioEventLoopGroup-3-2] Unhandled OF Message: OFFlowModFailedErrorMsgVer10(xid=140594, code=ALL_TABLES_FULL, data=OFFlowAddVer10(xid=140594, match=OFMatchV1Ver
10(in_port=5, eth_src=4e:84:03:d2:ec:75, eth_dst=ba:43:cb:45:4f:5d, eth_type=0x806), cookie=0x0020000000000000, idleTimeout=5, hardTimeout=0, priority=1, bufferId=4294967295, outPort=3, flags=[], 
actions=[OFActionOutputVer10(port=3, maxLen=65535)])) from OFSwitch DPID[00:00:00:00:00:00:00:01]
00:57:56.214 WARN [n.f.c.i.Controller:nioEventLoopGroup-3-2] Unhandled OF Message: OFFlowModFailedErrorMsgVer10(xid=140598, code=ALL_TABLES_FULL, data=OFFlowAddVer10(xid=140598, match=OFMatchV1Ver
10(in_port=5, eth_src=4e:84:03:d2:ec:75, eth_dst=ea:ae:6d:d5:5b:55, eth_type=0x806), cookie=0x0020000000000000, idleTimeout=5, hardTimeout=0, priority=1, bufferId=4294967295, outPort=3, flags=[], 
actions=[OFActionOutputVer10(port=3, maxLen=65535)])) from OFSwitch DPID[00:00:00:00:00:00:00:01]
00:57:56.214 INFO [n.f.d.i.Device:Scheduled-0] updateAttachmentPoint: ap [AttachmentPoint [sw=00:00:00:00:00:00:00:02, port=3, activeSince=Mon Sep 12 00:56:00 ART 2016, lastSeen=Mon Sep 12 00:57:5
5 ART 2016]]  newmap null 
00:57:56.215 INFO [n.f.d.i.Device:Scheduled-0] updateAttachmentPoint: ap [AttachmentPoint [sw=00:00:00:00:00:00:00:02, port=6, activeSince=Mon Sep 12 00:56:00 ART 2016, lastSeen=Mon Sep 12 00:57:5
5 ART 2016]]  newmap null 
00:57:56.215 INFO [n.f.d.i.Device:Scheduled-0] updateAttachmentPoint: ap [AttachmentPoint [sw=00:00:00:00:00:00:00:02, port=2, activeSince=Mon Sep 12 00:56:00 ART 2016, lastSeen=Mon Sep 12 00:57:5
5 ART 2016]]  newmap null 
00:57:56.215 INFO [n.f.d.i.Device:Scheduled-0] updateAttachmentPoint: ap [AttachmentPoint [sw=00:00:00:00:00:00:00:02, port=8, activeSince=Mon Sep 12 00:56:01 ART 2016, lastSeen=Mon Sep 12 00:57:5
5 ART 2016]]  newmap null 
00:57:56.229 ERROR [n.f.t.TopologyInstance:nioEventLoopGroup-3-6] {}
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key RouteId [src=00:00:00:00:00:00:00:06 dst=00:00:00:00:00:00:00:04].
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2407) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2375) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3990) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878) ~[floodlight.jar:na]
        at net.floodlightcontroller.topology.TopologyInstance.getRoute(TopologyInstance.java:906) [floodlight.jar:na]
        at net.floodlightcontroller.topology.TopologyInstance.getRoute(TopologyInstance.java:874) [floodlight.jar:na]
        at net.floodlightcontroller.topology.TopologyManager.getRoute(TopologyManager.java:699) [floodlight.jar:na]
        at net.floodlightcontroller.topology.TopologyManager.getRoute(TopologyManager.java:692) [floodlight.jar:na]
        at net.floodlightcontroller.forwarding.Forwarding.doForwardFlow(Forwarding.java:234) [floodlight.jar:na]
        at net.floodlightcontroller.forwarding.Forwarding.processPacketInMessage(Forwarding.java:124) [floodlight.jar:na]
        at net.floodlightcontroller.routing.ForwardingBase.receive(ForwardingBase.java:169) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.Controller.handleMessage(Controller.java:481) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchManager.handleMessage(OFSwitchManager.java:494) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.dispatchMessage(OFSwitchHandshakeHandler.java:1693) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.access$2200(OFSwitchHandshakeHandler.java:92) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$MasterState.processOFPacketIn(OFSwitchHandshakeHandler.java:1457) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$OFSwitchHandshakeState.processOFMessage(OFSwitchHandshakeHandler.java:849) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.processOFMessage(OFSwitchHandshakeHandler.java:1731) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.messageReceived(OFSwitchHandshakeHandler.java:1906) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFConnection.messageReceived(OFConnection.java:398) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFChannelHandler.sendMessageToConnection(OFChannelHandler.java:583) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFChannelHandler.access$800(OFChannelHandler.java:59) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFChannelHandler$OFChannelState.processOFMessage(OFChannelHandler.java:286) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:700) [floodlight.jar:na]
        at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:59) [floodlight.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:na]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:na]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:na]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [floodlight.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [floodlight.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [floodlight.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [floodlight.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [floodlight.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [floodlight.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [floodlight.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [floodlight.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
00:57:56.230 ERROR [n.f.t.TopologyInstance:nioEventLoopGroup-3-6] {}
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key RouteId [src=00:00:00:00:00:00:00:06 dst=00:00:00:00:00:00:00:05].
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2407) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2375) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3990) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994) ~[floodlight.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878) ~[floodlight.jar:na]
```

**Comment by rizard** [comment]
@mvanotti I'm not sure why all tables would be reported full. Can you try a simpler topology and a manual ping test to see if its anything specific to your script? For example, try a linear or tree topology manually by running mn in the terminal.
