### ISSUE TITLE
Property cookieMask not supported in version 1.0

### ISSUE THREAD

**Issue by allewwaly** [floodlight/floodlight#744]
2017-04-26 15:51:11.932 ERROR [n.f.l.i.LinkDiscoveryManager] Error in link discovery updates loop
java.lang.UnsupportedOperationException: Property cookieMask not supported in version 1.0
	at org.projectfloodlight.openflow.protocol.ver10.OFFlowDeleteVer10$Builder.setCookieMask(OFFlowDeleteVer10.java:506) ~[openflowj-3.0.0-SNAPSHOT.jar:na]
	at net.floodlightcontroller.forwarding.Forwarding.linkDiscoveryUpdate(Forwarding.java:966) ~[bin/:na]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.doUpdatesThread(LinkDiscoveryManager.java:908) [bin/:na]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.access$4(LinkDiscoveryManager.java:882) [bin/:na]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager$2.run(LinkDiscoveryManager.java:2103) [bin/:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_73]

**Comment by cbarrin** [comment]
What is the issue that you're trying to show? Is this related to any code that you've added?

**Comment by cbarrin** [comment]
I see where the potential problem area is. Can you, if possible, briefly explain what you did that caused this error? Thanks!

**Comment by allewwaly** [comment]
It locates at Forwarding.java, linkDiscoveryUpdate function.
Happens when using OF1.0 protocol.

msgs.add(srcSw.getOFFactory().buildFlowDelete()
                                        .setCookie(cookie)
                                        .setCookieMask(cookieMask)
                                        .setMatch(srcSw.getOFFactory().buildMatch()
                                                .setExact(MatchField.IN_PORT, u.getSrcPort())
                                                .build())
                                        .build());

It should check the OF version before setCookieMask(cookieMask), maybe change to:

msgs.add(sw2.getOFFactory().getVersion()
					.compareTo(OFVersion.OF_10) != 0 ? 
                                        srcSw.getOFFactory().buildFlowDelete()
                                        .setCookie(cookie)
                                        .setCookieMask(cookieMask)
                                        .setMatch(srcSw.getOFFactory().buildMatch()
                                                .setExact(MatchField.IN_PORT, u.getSrcPort())
                                                .build())
                                        .build());

**Comment by pchaigno** [comment]
@geddings Did you get a chance to look into this?

I have the same issue with Floodlight (commit 093c41bfef29417641f81791be811ec89ce2cf77) and [the default userspace Mininet switch](https://github.com/mininet/openflow) (OpenFlow 1.0). No application is running over Floodlight.

**Comment by QingWang0909** [comment]
@pchaigno 

Hey, do you mind to tell us the steps you did that cause this error? Thanks!

**Comment by pchaigno** [comment]
@QingWang0909 I've seen that you opened a pull request to fix this. Thanks!

Here are the steps I took to reproduce if you still need them:
```
shell1$ java -jar target/floodlight.jar

shell2$ sudo mn --switch user --controller=remote,ip=127.0.0.1,port=6653
mininet$ pingall
mininet$ ^D
```

At that point, in the Floodlight console, I get:
```
2017-12-25 16:56:47.454 INFO  [n.f.l.i.LinkDiscoveryManager] Sending LLDP packets out of all the enabled ports
2017-12-25 16:57:02.460 INFO  [n.f.l.i.LinkDiscoveryManager] Sending LLDP packets out of all the enabled ports
2017-12-25 16:57:08.183 ERROR [n.f.l.i.LinkDiscoveryManager] Error in link discovery updates loop
java.lang.UnsupportedOperationException: Property cookieMask not supported in version 1.0
	at org.projectfloodlight.openflow.protocol.ver10.OFFlowDeleteVer10$Builder.setCookieMask(OFFlowDeleteVer10.java:506) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.forwarding.Forwarding.linkDiscoveryUpdate(Forwarding.java:966) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.doUpdatesThread(LinkDiscoveryManager.java:908) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.access$200(LinkDiscoveryManager.java:123) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager$2.run(LinkDiscoveryManager.java:2103) [floodlight.jar:1.2-SNAPSHOT]
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) [na:na]
```

**Comment by QingWang0909** [comment]
@pchaigno Thanks for providing the steps! 

Yes I opened a pull request -- it should fix the error. It failed Travis tests at this point though -- I'll try to figure it out in next couple days. I'll greatly appreciate your patient!

**Comment by QingWang0909** [comment]
@pchaigno I just merged the pull request. This issue should be fixed. 

Thanks again for your patient!  Travis updated their build VM images in the middle of December, which caused our pull requests fail to pass the test. We rolled back the build VM image version to the previous version so now every tests have passed and the pull request been merged. Feel free to give a try.

**Comment by pchaigno** [comment]
Thanks @QingWang0909!
