### ISSUE TITLE
Problem in add a group by StaticEntryPusher 

### ISSUE THREAD

**Issue by JaunteZhou** [floodlight/floodlight#766]
I try to add a group. I use the command at https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/1343518/Static+Entry+Pusher+API 

I use Floodlight v1.2, so I change the URI. I use the command below (of course I changed the "switch" value)
curl -X POST -d '{"switch":"00:00:00:00:00:00:00:01", "entry_type":"group", "name":"group-mod-1", "active":"true", "group_type":"select", "group_id":"1",  "group_buckets":[ {"bucket_id":"1", "bucket_watch_group":"any", "bucket_weight":"50", "bucket_actions":"output=2"}, {"bucket_id":"2", "bucket_watch_group":"any", "bucket_weight":"50", "bucket_actions":"output=3"} ]}' http://<controller_ip>:8080/wm/staticflowpusher/json

It returns:
{"status":"Error! Could not parse flow mod, see log for details."}

and in floodlight log:
21:16:27.264 DEBUG [LogService:Dispatcher: Thread-15] Processing request to: "http://127.0.0.1:8080/wm/staticflowpusher/json"
21:16:27.532 ERROR [n.f.s.StaticFlowEntries:Dispatcher: Thread-15] Could not decode field from JSON string: entry_type
21:16:27.533 ERROR [n.f.s.StaticFlowEntries:Dispatcher: Thread-15] Could not decode field from JSON string: group_type
21:16:27.533 ERROR [n.f.s.StaticFlowEntries:Dispatcher: Thread-15] Could not decode field from JSON string: group_id
21:16:27.533 ERROR [n.f.s.StaticFlowEntries:Dispatcher: Thread-15] Could not decode field from JSON string: group_buckets
21:16:27.537 ERROR [n.f.s.w.StaticFlowEntryPusherResource:Dispatcher: Thread-15] Error parsing push flow mod request: {"switch":"00:00:42:09:f3:a5:84:40", "entry_type":"group", "name":"group-mod-1", "active":"true", "group_type":"select", "group_id":"1",  "group_buckets":[ {"bucket_id":"1", "bucket_watch_group":"any", "bucket_weight":"50", "bucket_actions":"output=2"}, {"bucket_id":"2", "bucket_watch_group":"any", "bucket_weight":"50", "bucket_actions":"output=3"} ]}
java.io.IOException: Expected FIELD_NAME
	at net.floodlightcontroller.staticflowentry.StaticFlowEntries.jsonToStorageEntry(StaticFlowEntries.java:627) ~[floodlight.jar:na]
	at net.floodlightcontroller.staticflowentry.web.StaticFlowEntryPusherResource.store(StaticFlowEntryPusherResource.java:297) ~[floodlight.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_151]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_151]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521) [floodlight.jar:na]
	at org.restlet.resource.ServerResource.post(ServerResource.java:1376) [floodlight.jar:na]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621) [floodlight.jar:na]
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679) [floodlight.jar:na]
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357) [floodlight.jar:na]
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044) [floodlight.jar:na]
	at org.restlet.resource.Finder.handle(Finder.java:236) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [floodlight.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [floodlight.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [floodlight.jar:na]
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75) [floodlight.jar:na]
	at org.restlet.Application.handle(Application.java:385) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [floodlight.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [floodlight.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [floodlight.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [floodlight.jar:na]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [floodlight.jar:na]
	at org.restlet.Component.handle(Component.java:408) [floodlight.jar:na]
	at org.restlet.Server.handle(Server.java:507) [floodlight.jar:na]
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63) [floodlight.jar:na]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143) [floodlight.jar:na]
	at org.restlet.ext.simple.internal.SimpleContainer.handle(SimpleContainer.java:74) [floodlight.jar:na]
	at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121) [floodlight.jar:na]
	at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103) [floodlight.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) [na:1.7.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) [na:1.7.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.7.0_151]
21:16:27.545 INFO [LogService:Dispatcher: Thread-15] 2017-11-29	21:16:27	127.0.0.1	-	-	8080	POST	/wm/staticflowpusher/json	-200	68	353	280	http://127.0.0.1:8080	curl/7.35.0	-

**Comment by geddings** [comment]
From the top of the page that you linked:
“Floodlight master branch as of mid-June 2016 supports pushing groups in addition to flows! We encourage you to upgrade if you're interested in this feature.”

The reason that you can’t insert a group is because you’re not using the master branch. Upgrade to master and it should work fine.

**Comment by JaunteZhou** [comment]
I'm so sorry. I only read the first notice but ignore the second one. First time when I get the floodlight from GitHub, I found it could not open the Web GUI. Then, I found someone said that is a bug of the code from GitHub. So, I try to use the v1.2 and I thought that the User Document is for the version 1.0-1.2&master. Thanks for your reply!
