### ISSUE TITLE
Can't run floodlight trought eclipse

### ISSUE THREAD

**Issue by Afladimir1** [floodlight/floodlight#782]
So i have been trying to use floodlight for the past few months and i was enable to use it in eclipse, so I decided to only the console and the curls commands for rules.
But now that i need to create a new module for my controller and i really need to fix the issues. Because after I do ant eclipse command and go to eclipse and import I can't run the controller any more it gives me this errors, and from this point foward the controller doesn't even work trough console.

> 2018-04-12 07:57:41.260 INFO  [n.f.c.m.FloodlightModuleLoader] Loading modules from src/main/resources/floodlightdefault.properties
2018-04-12 07:57:41.494 ERROR [n.f.c.m.FloodlightModuleLoader] Could not find module: net.floodlightcontroller.core.module.IFloodlightModule: Provider net.floodlightcontroller.staticentry.StaticEntryPusher could not be instantiated
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&signature in class file net/floodlightcontroller/dhcpserver/DHCPServer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.findAllModules(FloodlightModuleLoader.java:144)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:277)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:235)
	at net.floodlightcontroller.core.Main.main(Main.java:61)

There are other errors in the project which I find it weird because It's the original project from github.floo
I used the installation guide, and I'm using floodlight VM with mininet.
This is urgent, this project is for my thesis,  if you could help me I would appreciate.

Thanks in advance.

![image](https://user-images.githubusercontent.com/17175453/38676392-cc034912-3e52-11e8-9d9a-7bb902c8bdc7.png)

**Comment by QingWang0909** [comment]
@Afladimir1 Try to clone a fresh new copy from our master branch and rebuild it (make sure you followed the tutorial for each steps), see if that works. If it is not work, please email our emailing list: (floodlight-dev@openflowhub.org) -- we'll happy to help you there. The Issue usually is the place to report bugs. Thanks!
