### ISSUE TITLE
Installing floodlight in ubuntu 14.04?

### ISSUE THREAD

**Issue by raghdaaljaff** [floodlight/floodlight#813]

**Comment by raghdaaljaff** [comment]
hello iam staudent and iam trying to install the floodlight controller in the ubuntu 14.04 in my vm and when i wrote the command are these log is right or something error 
pythonnetwork@ubuntu:~/floodlight$ java -jar target/floodlight.jar
2019-01-06 05:08:09.113 INFO  [n.f.c.m.FloodlightModuleLoader] Loading modules from src/main/resources/floodlightdefault.properties
2019-01-06 05:08:10.439 ERROR [n.f.c.m.FloodlightModuleLoader] Could not find module: net.floodlightcontroller.core.module.IFloodlightModule: Provider net.floodlightcontroller.staticentry.StaticEntryPusher could not be instantiated
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&signature in class file net/floodlightcontroller/forwarding/Forwarding
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.findAllModules(FloodlightModuleLoader.java:144)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:277)
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:235)
	at net.floodlightcontroller.core.Main.main(Main.java:61)

**Comment by raghdaaljaff** [comment]
Any help ?

**Comment by raghdaaljaff** [comment]
@rizard

**Comment by qingwang-bsn** [comment]
Where did you run into this problem, CLI or Eclipse?

**Comment by raghdaaljaff** [comment]
Cli 

Regards.

**Comment by qingwang-bsn** [comment]
Try to pull all update from Floodlight and then rebuild it, see if that works.

**Comment by raghdaaljaff** [comment]
@Qing Wang How I can to pull the floodlight update? 

Regards.

**Comment by qingwang-bsn** [comment]
You shall use the git pull command.

**Comment by raghdaaljaff** [comment]
Thanks for reply but I already installed the master branch 

Regards.

**Comment by qingwang-bsn** [comment]
"git pull" can be used to update your local branch, so it can sync up w/ remote repository (which is master branch at Floodlight repo)

**Comment by raghdaaljaff** [comment]
Ok thanks so much 

Regards.
