### ISSUE TITLE
11:05:10.596 INFO [n.f.c.i.OFChannelHandler:nioEventLoopGroup-3-1] [[? from 127.0.0.1:50500]] Disconnected connection

### ISSUE THREAD

**Issue by pranshu2019** [floodlight/floodlight#852]
I have  installed floodlight on my ubuntu 20.4 virtual Machine . When i try to Create mininet topology with floodlight remote controller using following command " sudo mn --controlle=remote,ip=127.0.0.1,port=6653 --topo=single,3 " . I get the following error.
1:09:47.571 INFO [n.f.c.i.OFChannelHandler:nioEventLoopGroup-3-2] New switch connection from /127.0.0.1:50566
11:09:47.579 ERROR [n.f.c.i.OFChannelHandler:nioEventLoopGroup-3-2] Error while processing message from switch [? from 127.0.0.1:50566]state net.floodlightcontroller.core.internal.OFChannelHandler$WaitHelloState@1dc2b69f
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown wire version: 6
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358) ~[floodlight.jar:1.2]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) ~[floodlight.jar:1.2]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [floodlight.jar:1.2]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [floodlight.jar:1.2]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [floodlight.jar:1.2]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [floodlight.jar:1.2]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [floodlight.jar:1.2]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [floodlight.jar:1.2]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [floodlight.jar:1.2]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [floodlight.jar:1.2]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: Unknown wire version: 6
        at org.projectfloodlight.openflow.protocol.OFFactories$GenericReader.readFrom(OFFactories.java:72) ~[floodlight.jar:1.2]
        at org.projectfloodlight.openflow.protocol.OFFactories$GenericReader.readFrom(OFFactories.java:49) ~[floodlight.jar:1.2]
        at net.floodlightcontroller.core.internal.OFMessageDecoder.decode(OFMessageDecoder.java:80) ~[floodlight.jar:1.2]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327) ~[floodlight.jar:1.2]
        ... 12 common frames omitted
11:09:47.584 INFO [n.f.c.i.OFChannelHandler:nioEventLoopGroup-3-2] [[? from 127.0.0.1:50566]] Disconnected connection

**Comment by McmillanTAC** [comment]
I also had this problem,and I found that the error message contained  "Unknown wire version: 6". I guessed it may be related to the version of OpenFlow protocol used by OpenvSwitch,so I tried to use the command "ovs-vsctl set bridge br0 protocols=OpenFlow13 " to lower the OpenFlow protocol version,and it worked.
Notes:floodlight version:v1.2 OpenvSwitch version:2.13.4
