### ISSUE TITLE
Frequent disconnection with the latest OVS

### ISSUE THREAD

**Issue by ayyoob** [floodlight/floodlight#853]
I was trying floodlight with the latest OVS and the below error is thrown and leads to connection loss. However when I try it with OVS 2.9 version then it works fine, Could you please point me towards resources on how I can resolve this issue.

2021-02-07 17:59:50.115 ERROR [n.f.c.i.OFChannelHandler] Error while processing message from switch [00:00:XX:XX:XX:XX:XX:ea(0x0) from 172.18.0.1:54514]state net.floodlightcontroller.core.internal.OFChannelHandler$CompleteState@6a776bca
io.netty.handler.codec.DecoderException: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator experimenter of class OFExperimenterVer13: 1330529792
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator experimenter of class OFExperimenterVer13: 1330529792
at org.projectfloodlight.openflow.protocol.ver13.OFExperimenterVer13$Reader.readFrom(OFExperimenterVer13.java:66)
at org.projectfloodlight.openflow.protocol.ver13.OFMessageVer13$Reader.readFrom(OFMessageVer13.java:69)
at org.projectfloodlight.openflow.protocol.ver13.OFMessageVer13$Reader.readFrom(OFMessageVer13.java:39)
at net.floodlightcontroller.core.internal.OFMessageDecoder.decode(OFMessageDecoder.java:80)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
... 17 common frames omitted

**Comment by ayyoob** [comment]
Resolved with assigning roles
