### ISSUE TITLE
When switch connecting floodlight, error occurs

### ISSUE THREAD

**Issue by dedlyfish** [floodlight/floodlight#862]
I have installed floodlight on ubuntu pc, and trying to configure my switches to work with it. But, when I enable openflow 1.3, switches fail to connect, but openflow 1.0 works fine...

Is there any suggestions?
Thank you for any help!

2022-05-11 08:17:58.139 ERROR [n.f.c.i.OFChannelHandler] Error while processing message from switch [00:00:00:1e:08:16:af:0c(0x0) from 10.243.173.4:37350]state net.floodlightcontroller.core.internal.OFChannelHandler$CompleteState@569840dd
io.netty.handler.codec.DecoderException: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator subtype of class OFActionIdNiciraVer13: 25
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[floodlight.jar:1.2-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [floodlight.jar:1.2-SNAPSHOT]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [floodlight.jar:1.2-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
Caused by: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator subtype of class OFActionIdNiciraVer13: 25
        at org.projectfloodlight.openflow.protocol.ver13.OFActionIdNiciraVer13$Reader.readFrom(OFActionIdNiciraVer13.java:62) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFActionIdExperimenterVer13$Reader.readFrom(OFActionIdExperimenterVer13.java:59) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFActionIdVer13$Reader.readFrom(OFActionIdVer13.java:50) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFActionIdVer13$Reader.readFrom(OFActionIdVer13.java:39) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.util.ChannelUtils.readList(ChannelUtils.java:66) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturePropWriteActionsVer13$Reader.readFrom(OFTableFeaturePropWriteActionsVer13.java:192) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturePropVer13$Reader.readFrom(OFTableFeaturePropVer13.java:86) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturePropVer13$Reader.readFrom(OFTableFeaturePropVer13.java:39) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.util.ChannelUtils.readList(ChannelUtils.java:66) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturesVer13$Reader.readFrom(OFTableFeaturesVer13.java:506) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturesVer13$Reader.readFrom(OFTableFeaturesVer13.java:484) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.util.ChannelUtils.readList(ChannelUtils.java:66) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFTableFeaturesStatsReplyVer13$Reader.readFrom(OFTableFeaturesStatsReplyVer13.java:303) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFStatsReplyVer13$Reader.readFrom(OFStatsReplyVer13.java:103) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFMessageVer13$Reader.readFrom(OFMessageVer13.java:54) ~[floodlight.jar:1.2-SNAPSHOT]
        at org.projectfloodlight.openflow.protocol.ver13.OFMessageVer13$Reader.readFrom(OFMessageVer13.java:39) ~[floodlight.jar:1.2-SNAPSHOT]
        at net.floodlightcontroller.core.internal.OFMessageDecoder.decode(OFMessageDecoder.java:80) ~[floodlight.jar:1.2-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[floodlight.jar:1.2-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[floodlight.jar:1.2-SNAPSHOT]

**Comment by john-github-2020** [comment]
I have the same problem.
