### ISSUE TITLE
Unknown value for discriminator typeLen of class OFOxmVer15: 82436

### ISSUE THREAD

**Issue by YoanisWolde** [floodlight/floodlight#863]
hello,
I am using floodlight from master( floodlight 1.2-SNAPSHOT, Ubuntu 20.04LTS, and Open vSwitch 2.12.5. when i try to create tree topology with depth=2 and fanout=2 the controller display error **"ERROR [n.f.c.i.OFChannelHandler] Error while processing message from switch [00:00:00:00:00:00:00:01(0x0) from 127.0.0.1:58914]state net.floodlightcontroller.core.internal.OFChannelHandler$CompleteState@3652b032
io.netty.handler.codec.DecoderException: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator typeLen of class OFOxmVer15: 82436**
 
I am really need the help.

2022-06-04 17:00:44.456 INFO  [n.f.c.m.FloodlightModuleLoader] Loading modules from src/main/resources/floodlightdefault.properties
2022-06-04 17:00:44.727 WARN  [n.f.r.RestApiServer] HTTPS disabled; HTTPS will not be used to connect to the REST API.
2022-06-04 17:00:44.728 WARN  [n.f.r.RestApiServer] HTTP enabled; Allowing unsecure access to REST API on port 8080.
2022-06-04 17:00:44.728 WARN  [n.f.r.RestApiServer] CORS access control allow ALL origins: true
2022-06-04 17:00:45.12 WARN  [n.f.c.i.OFSwitchManager] SSL disabled. Using unsecure connections between Floodlight and switches.
2022-06-04 17:00:45.12 INFO  [n.f.c.i.OFSwitchManager] Clear switch flow tables on initial handshake as master: TRUE
2022-06-04 17:00:45.12 INFO  [n.f.c.i.OFSwitchManager] Clear switch flow tables on each transition to master: TRUE
2022-06-04 17:00:45.12 INFO  [n.f.c.i.OFSwitchManager] Setup default rules for all tables on switch connect: true
2022-06-04 17:00:45.26 INFO  [n.f.c.i.OFSwitchManager] Setting 0x1 as the default max tables to receive table-miss flow
2022-06-04 17:00:45.116 INFO  [n.f.c.i.OFSwitchManager] OpenFlow version OF_15 will be advertised to switches. Supported fallback versions [OF_10, OF_11, OF_12, OF_13, OF_14, OF_15]
2022-06-04 17:00:45.118 INFO  [n.f.c.i.OFSwitchManager] Listening for OpenFlow switches on [0.0.0.0]:6653
2022-06-04 17:00:45.118 INFO  [n.f.c.i.OFSwitchManager] OpenFlow socket config: 1 boss thread(s), 16 worker thread(s), 60000 ms TCP connection timeout, max 1000 connection backlog, 4194304 byte TCP send buffer size
2022-06-04 17:00:45.119 INFO  [n.f.c.i.Controller] ControllerId set to 1
2022-06-04 17:00:45.120 INFO  [n.f.c.i.Controller] Shutdown when controller transitions to STANDBY HA role: true
2022-06-04 17:00:45.120 WARN  [n.f.c.i.Controller] Controller will automatically deserialize all Ethernet packet-in messages. Set 'deserializeEthPacketIns' to 'FALSE' if this feature is not required or when benchmarking core performance
2022-06-04 17:00:45.120 INFO  [n.f.c.i.Controller] Controller role set to ACTIVE
2022-06-04 17:00:45.196 INFO  [n.f.l.i.LinkDiscoveryManager] Link latency history set to 10 LLDP data points
2022-06-04 17:00:45.200 INFO  [n.f.l.i.LinkDiscoveryManager] Latency update threshold set to +/-0.5 (50.0%) of rolling historical average
2022-06-04 17:00:45.202 INFO  [n.f.t.TopologyManager] Path metrics set to LATENCY
2022-06-04 17:00:45.202 INFO  [n.f.t.TopologyManager] Will compute a max of 3 paths upon topology updates
2022-06-04 17:00:45.217 INFO  [n.f.f.Forwarding] Default hard timeout not configured. Using 0.
2022-06-04 17:00:45.217 INFO  [n.f.f.Forwarding] Default idle timeout set to 5.
2022-06-04 17:00:45.217 INFO  [n.f.f.Forwarding] Default table ID not configured. Using 0x0.
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Default priority not configured. Using 1.
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Default flags will be set to SEND_FLOW_REM true.
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Default flow matches set to: IN_PORT=true, VLAN=true, MAC=true, IP=true, FLAG=true, TPPT=true
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Default detailed flow matches set to: SRC_MAC=true, DST_MAC=true, SRC_IP=true, DST_IP=true, SRC_TPPT=true, DST_TPPT=true
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Not flooding ARP packets. ARP flows will be inserted for known destinations
2022-06-04 17:00:45.218 INFO  [n.f.f.Forwarding] Flows will be removed on link/port down events
2022-06-04 17:00:45.218 INFO  [n.f.s.StatisticsCollector] Statistics collection enabled
2022-06-04 17:00:45.218 INFO  [n.f.s.StatisticsCollector] Port statistics collection interval set to 10s
2022-06-04 17:00:45.220 INFO  [n.f.h.HAController] Configuration parameters: {serverPort=127.0.0.1:4242, nodeid=1} 1 
2022-06-04 17:00:45.292 INFO  [o.s.s.i.SyncManager] [1] Updating sync configuration ClusterConfig [allNodes={1=Node [hostname=192.168.56.1, port=6642, nodeId=1, domainId=1], 2=Node [hostname=192.168.56.1, port=6643, nodeId=2, domainId=1], 3=Node [hostname=192.168.56.1, port=6644, nodeId=3, domainId=1], 4=Node [hostname=192.168.56.1, port=6645, nodeId=4, domainId=1]}, authScheme=CHALLENGE_RESPONSE, keyStorePath=/etc/floodlight/myKey.jceks, keyStorePassword is set]
2022-06-04 17:00:45.508 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x6ff5c70d]'
2022-06-04 17:00:45.508 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'TCP_NODELAY' for channel '[id: 0x6ff5c70d]'
2022-06-04 17:00:45.508 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'SO_SNDBUF' for channel '[id: 0x6ff5c70d]'
2022-06-04 17:00:45.519 INFO  [o.s.s.i.r.RPCService] Listening for internal floodlight RPC on 0.0.0.0/0.0.0.0:6642
2022-06-04 17:00:45.533 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xbcbc2bc1]'
2022-06-04 17:00:45.533 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'TCP_NODELAY' for channel '[id: 0xbcbc2bc1]'
2022-06-04 17:00:45.533 WARN  [i.n.b.ServerBootstrap] Unknown channel option 'SO_SNDBUF' for channel '[id: 0xbcbc2bc1]'
2022-06-04 17:00:45.601 WARN  [n.f.s.StatisticsCollector] Statistics collection thread(s) started
2022-06-04 17:00:45.612 INFO  [n.f.h.HAController] LDHAWorker is starting...
2022-06-04 17:00:45.624 INFO  [n.f.h.HAController] TopoHAWorker is starting...
2022-06-04 17:00:45.672 INFO  [n.f.h.AsyncElection] [AsyncElection] Priorities are not set.
2022-06-04 17:00:45.681 INFO  [n.f.h.HAController] HAController is starting...
2022-06-04 17:00:45.700 INFO  [n.f.h.ControllerLogic] [ControllerLogic] Running...
2022-06-04 17:00:45.717 INFO  [n.f.h.HAServer] Starting HAServer...
2022-06-04 17:00:45.908 INFO  [o.r.C.I.Server] Starting the Simple [HTTP/1.1] server on port 8080
2022-06-04 17:00:45.909 INFO  [org.restlet] Starting net.floodlightcontroller.restserver.RestApiServer$RestApplication application
2022-06-04 17:00:50.430 INFO  [n.f.j.JythonServer] Starting DebugServer on :6655
2022-06-04 17:01:00.590 INFO  [n.f.l.i.LinkDiscoveryManager] Sending LLDP packets out of all the enabled ports
2022-06-04 17:01:14.276 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:58952
2022-06-04 17:01:14.327 INFO  [n.f.c.i.OFChannelHandler] [[? from 127.0.0.1:58952]] Disconnected connection
2022-06-04 17:01:14.688 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:58954
2022-06-04 17:01:14.699 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:58956
2022-06-04 17:01:14.706 INFO  [n.f.c.i.OFChannelHandler] Negotiated equal OpenFlow version of OF_15 for /127.0.0.1:58954 using lesser hello header algorithm.
2022-06-04 17:01:14.726 INFO  [n.f.c.i.OFChannelHandler] Negotiated equal OpenFlow version of OF_15 for /127.0.0.1:58956 using lesser hello header algorithm.
2022-06-04 17:01:14.789 INFO  [n.f.c.i.OFChannelHandler] New switch connection from /127.0.0.1:58958
2022-06-04 17:01:14.792 INFO  [n.f.c.i.OFChannelHandler] Negotiated equal OpenFlow version of OF_15 for /127.0.0.1:58958 using lesser hello header algorithm.
2022-06-04 17:01:14.895 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Switch OFSwitch DPID[00:00:00:00:00:00:00:02] bound to class class net.floodlightcontroller.core.internal.OFSwitch, description SwitchDescription [manufacturerDescription=Nicira, Inc., hardwareDescription=Open vSwitch, softwareDescription=2.12.5, serialNumber=None, datapathDescription=s2]
2022-06-04 17:01:14.895 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Switch OFSwitch DPID[00:00:00:00:00:00:00:03] bound to class class net.floodlightcontroller.core.internal.OFSwitch, description SwitchDescription [manufacturerDescription=Nicira, Inc., hardwareDescription=Open vSwitch, softwareDescription=2.12.5, serialNumber=None, datapathDescription=s3]
2022-06-04 17:01:14.897 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Switch OFSwitch DPID[00:00:00:00:00:00:00:01] bound to class class net.floodlightcontroller.core.internal.OFSwitch, description SwitchDescription [manufacturerDescription=Nicira, Inc., hardwareDescription=Open vSwitch, softwareDescription=2.12.5, serialNumber=None, datapathDescription=s1]
2022-06-04 17:01:14.898 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Defining switch role from config file: ROLE_MASTER
2022-06-04 17:01:14.898 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Defining switch role from config file: ROLE_MASTER
2022-06-04 17:01:14.898 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Defining switch role from config file: ROLE_MASTER
2022-06-04 17:01:14.911 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Clearing flow tables of 00:00:00:00:00:00:00:01 on upcoming transition to MASTER.
2022-06-04 17:01:14.911 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Clearing flow tables of 00:00:00:00:00:00:00:02 on upcoming transition to MASTER.
2022-06-04 17:01:14.916 INFO  [n.f.c.i.OFSwitchHandshakeHandler] Clearing flow tables of 00:00:00:00:00:00:00:03 on upcoming transition to MASTER.
2022-06-04 17:01:15.208 ERROR [n.f.c.i.OFChannelHandler] Error while processing message from switch [00:00:00:00:00:00:00:01(0x0) from 127.0.0.1:58954]state net.floodlightcontroller.core.internal.OFChannelHandler$CompleteState@231f1738
i**o.netty.handler.codec.DecoderException: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator typeLen of class OFOxmVer15: 82436
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [floodlight.jar:1.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
Caused by: org.projectfloodlight.openflow.exceptions.OFParseError: Unknown value for discriminator typeLen of class OFOxmVer15: 82436
	at org.projectfloodlight.openflow.protocol.ver15.OFOxmVer15$Reader.readFrom(OFOxmVer15.java:546) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.OFOxmVer15$Reader.readFrom(OFOxmVer15.java:38) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.util.ChannelUtils.readList(ChannelUtils.java:67) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.OFOxmList.readFrom(OFOxmList.java:103) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.OFMatchV3Ver15$Reader.readFrom(OFMatchV3Ver15.java:598) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.ChannelUtilsVer15.readOFMatch(ChannelUtilsVer15.java:17) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.OFPacketInVer15$Reader.readFrom(OFPacketInVer15.java:546) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.OFMessageVer15$Reader.readFrom(OFMessageVer15.java:99) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.ver15.OFMessageVer15$Reader.readFrom(OFMessageVer15.java:39) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.OFFactories$GenericReader.readFrom(OFFactories.java:81) ~[floodlight.jar:1.2-SNAPSHOT]
	at org.projectfloodlight.openflow.protocol.OFFactories$GenericReader.readFrom(OFFactories.java:53) ~[floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFMessageDecoder.decode(OFMessageDecoder.java:80) ~[floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[floodlight.jar:1.2-SNAPSHOT]
	... 17 common frames omitted**

**Comment by DanielHelmig** [comment]
For anyone stumbling across this issue years later (like me):

Open vSwitch sometimes seems to add data to the skb_mark field, in my case this happened for some ICMPv6 packets.
If this field is not 0 it gets passed along as match field in the PACKET_IN message towards Floodlight. 
This skb_mark can be matched by Open vSwitch as part of the pkt_mark field (see https://www.openvswitch.org/support/dist-docs/ovs-fields.7.txt)

The OpenflowJ version Floodlight uses does not recognize this match field. The solution is to either disable IPv6 or generate a new version of OpenflowJ using Loxigen.

To do so add the following structs to the openflow_input folder:

struct of_oxm_skb_packet_mark : of_oxm {
	uint32_t type_len == 0x00014204;
	uint32_t value;
};

struct of_oxm_skb_packet_mark_masked : of_oxm {
	uint32_t type_len == 0x00014308;
	uint32_t value;
	uint32_t value_mask;
};

Add the respective entries to java_gen/java_type.py:

'of_oxm_skb_packet_mark' : { 'value' : u32obj },
'of_oxm_skb_packet_mark_masked' : { 'value' : u32obj, 'value_mask' : u32obj },

Append the MatchField class in java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchField.java
public final static MatchField<U32> SKB_PACKET_MARK = new MatchField<>("skb_packet_mark", MatchFields.SKB_PACKET_MARK);

And finally append the MatchFields enum with SKB_PACKET_MARK

Then generate a new version of OpenflowJ and use this version as library for Floodlight.
